# Permalinks
#permalink:        pretty

# Theme
theme:            jekyll-theme-minimal

# Setup
title:            "Rakendustarkvara: R, 2025 sÃ¼gis"
tagline:          LTMS.00.016
url:              http://rkursus.github.io/
paginate:         1
baseurl:          /2025
author:
  name:           Anne Selart
  url:            
  email:          anne.selart@ut.ee

# Custom vars
version:          1.0.0
github:
  repo:           http://rkursus.github.io/2024

pages_list:       
  Praktikumid: '/praktikumid'
  Projektid: '/projektid'
